import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import { ThemeContext } from "@/contexts/themecontext";
import { UserProvider } from "@/contexts/UserContext";
import DesignerContextProvider from "@/contexts/DesignerContext";

import Header from "@/components/ui/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
  display: "swap",
});
const nunito = Nunito({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${nunito.variable}  w-full h-full `}>
          <UserProvider>
        <ThemeContext>
            <DesignerContextProvider>
              {" "}
               {children}{" "}
            </DesignerContextProvider>
        </ThemeContext>
          </UserProvider>
      </body>
    </html>
  );
}
